
services:
  nginx_pro:
    container_name: nginx_pro
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    # Nginx is linked to repo containers
    depends_on:
      - backend
    platform: linux/amd64

  backend:
    container_name: backend
    restart: always
    build:
      dockerfile: ./dockerfile
    platform: linux/amd64

    environment:
      - NODE_ENV=production
      - OWNER=$OWNER
      - OWNER_PK=$OWNER_PK
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - X_APP_KEY=$X_APP_KEY
      - X_APP_SECRET=$X_APP_SECRET
      - X_ACCESS_TOKEN=$X_ACCESS_TOKEN
      - X_ACCESS_SECRET=$X_ACCESS_SECRET
